CREATE DATABASE IF NOT EXISTS $ENV_WORDPRESS_DATABASE;
CREATE USER IF NOT EXISTS "$ENV_WORDPRESS_USER"@"$ENV_HOSTNAME" IDENTIFIED BY "$ENV_DATABASE_PASSWORD";
GRANT ALL PRIVILEGES ON $ENV_WORDPRESS_DATABASE.* TO "$ENV_WORDPRESS_USER"@"$ENV_HOSTNAME";
FLUSH PRIVILEGES;
